stolostron/openshift-pipelines

singapore-gateway-pipelines/pipeline_sgs_prod.yaml
singapore-gateway-pipelines/resources/multiclusterengine/mce-argo.yaml
singapore-gateway-pipelines/resources/operators/multicluster-engine/catalogsource.yaml
singapore-gateway-pipelines/tasks_prod.yaml

Manual updates for prod

---

singapore-gateway-pipelines/pipeline_sgs_prod.yaml
singapore-gateway-pipelines/pipeline_sgs_staging.yaml
singapore-gateway-pipelines/tasks_prod.yaml

Update prod tasks

---

singapore-gateway-pipelines/resources/cluster-registration-operator/rbac.yaml

Update ClusterRegistration RBAC

---

singapore-gateway-pipelines/resources/cluster-registration-operator/rbac.yaml

Add update and finalizer permission

---

singapore-gateway-pipelines/resources/cluster-registration-operator/rbac.yaml

update cluster-registration rbac

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/tasks.yaml

update kcp-pipeline tasks

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/prereqs/secrets_template.yaml
kcp-sgs-pipelines/resources/hypershift-addon.yaml
kcp-sgs-pipelines/tasks.yaml

Apply HyperDeploy

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/kcp-sgs-sre-rbac.yaml
kcp-sgs-pipelines/tasks.yaml

Configure Azure HD & GH RBAC

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/observability_secret.yaml
kcp-sgs-pipelines/tasks.yaml

Update Obs prereqs

---

kcp-sgs-pipelines/resources/multiclusterobservability.yaml
kcp-sgs-pipelines/tasks.yaml

install-mco

---

.github/workflows/build_and_publish.yml
ocm-utils/Dockerfile

Fix Image Vulnerabilities

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/alertmanager-to-github/body.tmpl
kcp-sgs-pipelines/resources/alertmanager.yaml
kcp-sgs-pipelines/tasks.yaml

Add Alert Manager

---

kcp-sgs-pipelines/README.md
kcp-sgs-pipelines/prereqs/secrets_template.yaml
kcp-sgs-pipelines/resources/kcp-sgs-sre-rbac.yaml
kcp-sgs-pipelines/tasks.yaml

Add Readme

---

autoscale-hypershift/main.go
autoscale-hypershift/pipeline/pipeline.yaml
autoscale-hypershift/pipeline/prereqs/secrets_template.yaml
autoscale-hypershift/pipeline/resources/openshift-gitops-sub.yaml
autoscale-hypershift/pipeline/tasks.yaml
autoscale-hypershift/pipeline/test_pipeline.yaml

WIP Initial Test

---

autoscale-hypershift/pipeline/resources/operators/advanced-cluster-management/multiclusterhub.yaml
autoscale-hypershift/pipeline/tasks.yaml
autoscale-hypershift/pipeline/test_pipeline.yaml

Refctor tasks

---

autoscale-hypershift/pipeline/resources/hypershift-addon.yaml
autoscale-hypershift/pipeline/tasks.yaml
autoscale-hypershift/pipeline/test_pipeline.yaml

Add HD Prereqs

---

autoscale-hypershift/pipeline/tasks.yaml
autoscale-hypershift/pipeline/test_pipeline.yaml
kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/acm-argo.yaml
kcp-sgs-pipelines/resources/argo-rbac.yaml
kcp-sgs-pipelines/resources/openshift-gitops-sub.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/acm-catalogsource.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/acm-subscription.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/mce-catalogsource.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/multiclusterhub.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/operatorgroup.yaml
kcp-sgs-pipelines/tasks.yaml

Refactor KCP-SGS Pipeline

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/hypershift/azr-hypershiftdeployment.yaml
kcp-sgs-pipelines/tasks.yaml

Update naming and fix secret name

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/tasks.yaml

switch clusterpool

---

autoscale-hypershift/templates/cluster-scoped-cronjob.yaml
autoscale-hypershift/templates/cronjobs.yaml
autoscale-hypershift/templates/job-scale-up.yaml
kcp-sgs-pipelines/tasks.yaml

Version image

---

kcp-sgs-pipelines/resources/operators/singapore/clusterrole.yaml
kcp-sgs-pipelines/resources/operators/singapore/clusterrolebinding.yaml
kcp-sgs-pipelines/resources/operators/singapore/deployment.yaml
kcp-sgs-pipelines/resources/operators/singapore/role.yaml
kcp-sgs-pipelines/resources/operators/singapore/rolebinding.yaml
kcp-sgs-pipelines/resources/operators/singapore/serviceaccount.yaml
kcp-sgs-pipelines/resources/sinagpore-argo.yaml
kcp-sgs-pipelines/resources/singapore-secret.yaml
kcp-sgs-pipelines/tasks.yaml

Add Singapore

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/policies/encrypt-etcd.yaml
kcp-sgs-pipelines/tasks.yaml

Encrypt Etcd

---

kcp-sgs-pipelines/resources/hypershift/azr-hypershiftdeployment.yaml
kcp-sgs-pipelines/resources/operators/singapore/deployment.yaml
singapore-gateway-pipelines/pipeline_integration.yaml
singapore-gateway-pipelines/pipeline_sgs_prod.yaml
singapore-gateway-pipelines/tasks_integration.yaml

Add Integration & Change Azure Region

---

kcp-sgs-pipelines/resources/hypershift/kcp-unstable-hypershiftdeployment.yaml
kcp-sgs-pipelines/tasks.yaml

add kcp-unstable hd

---

kcp-sgs-pipelines/resources/hypershift/kcp-unstable-hypershiftdeployment.yaml

Add kcp unstable hd

---

autoscale-hypershift/templates/cronjobs.yaml

Fix Cronjobs

---

kcp-ns-cleanup/templates/job-kcp-ns-cleanup.yaml
kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/README.md
kcp-sgs-pipelines/resources/policies/acm-hardening/input-backup/policy-backup.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/input-managedcluster/policy-managedclusteraddon-available.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/input-policyreport/policy-check-policyreports.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/input-subscriptions/policy-subscriptions.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/input/placement.yaml
kcp-sgs-pipelines/resources/policies/acm-hardening/kustomization.yml
kcp-sgs-pipelines/resources/policies/acm-hardening/policyGenerator.yaml
kcp-sgs-pipelines/tasks.yaml

refactor alertmanager

---

kcp-sgs-pipelines/resources/policies/acm-hardening/input/placement.yaml
kcp-sgs-pipelines/tasks.yaml

fix acm-hardening policy

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/resources/argo/cluster-backup.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/multiclusterhub.yaml
kcp-sgs-pipelines/resources/operators/cluster-backup/data-protection-application.yaml
kcp-sgs-pipelines/tasks.yaml

Onboard BackupAndRestore

---

kcp-sgs-pipelines/resources/operators/cluster-backup/backupschedule.yaml
kcp-sgs-pipelines/tasks.yaml

add backupschedule

---

addon-bundling/config.yaml
kcp-ns-cleanup/go.mod
kcp-ns-cleanup/main.go
kcp-sgs-pipelines/resources/argo/cert-manager.yaml
kcp-sgs-pipelines/resources/operators/cert-manager/namespace.yaml
kcp-sgs-pipelines/resources/operators/cert-manager/operatorgroup.yaml
kcp-sgs-pipelines/resources/operators/cert-manager/subscription.yaml

Onboard Cert-manager

---

kcp-sgs-pipelines/resources/operators/cert-manager/aws.clusterissuer.yaml

add PrivateKeyRef

---

kcp-sgs-pipelines/resources/operators/cert-manager/crds.yaml
kcp-sgs-pipelines/resources/operators/cert-manager/policy-copy.yaml

Fix Cert-manager OutOfSync

---

kcp-sgs-pipelines/resources/operators/policies/policy-copy.yaml

Fix Policy Argo OutOfSync

---

kcp-sgs-pipelines/resources/operators/observability/obs_secrets.yaml

Fix Spacing

---

kcp-sgs-pipelines/pipeline.yaml
kcp-sgs-pipelines/tasks.yaml

Refactor Obs

---

kcp-sgs-pipelines/resources/operators/policies/alertmanager.yaml

Remove unused reciever

---

addon-bundling/Makefile
addon-bundling/requirements.txt
addon-bundling/update-config.py

Add UpdateConfig

---

kcp-sgs-pipelines/resources/operators/advanced-cluster-management/acm-catalogsource.yaml
kcp-sgs-pipelines/resources/operators/advanced-cluster-management/mce-catalogsource.yaml
kcp-sgs-pipelines/resources/operators/singapore/clusterrolebinding-stable.yaml
kcp-sgs-pipelines/resources/operators/singapore/clusterrolebinding-unstable.yaml

Update ACM & Fix KCP RBAC

---

kcp-sgs-pipelines/resources/operators/policies/alertmanager.yaml

Confirming GH account switched to open issues with bot account

temporary - for testing

---

kcp-sgs-pipelines/resources/operators/policies/alertmanager.yaml

Restore Dev settings

---

addon-bundling/retrieve-ds-bundles.sh

Fix tar cmd

---

ocm-utils/Dockerfile

Useful for making pull-requests and merge-requests

Add 'hub' cli

---

addon-bundling/config.yaml

Update all bundles

---

kcp-sgs-pipelines/resources/operators/singapore/deployment-unstable.yaml

Signed-off-by: Robin Y Bobbitt <rbobbitt@redhat.com>

bump singapore in kcp-unstable for SyncTarget rename

---

ocm-utils/Dockerfile

Note: At the time of the PR, the build fails parsing †he gpg key. So for now, I disable the gpg check for the google repo.

update gcloud install

---

addon-bundling/config-dash.yaml

deliver 2.7.0 DOWNSTREAM v2.7.0 241

---

addon-bundling/config-dash.yaml

add pre6 2.7.0 DOWNSTREAM 2022-12-20-03-44-40

---

addon-bundling/config-dash.yaml

tags: 2.7.0-DOWNSTREAM-2023-01-03-01-19-39 and v2.7.0-FC17
Upstream Edge Snapshot: 2.7.0-SNAPSHOT-2023-01-03-01-19-39
Embedded MCE build: 2.2.0-DOWNANDBACK-2023-01-03-02-48-16 and v2.2.0-FC17
Bundle NVR: acm-operator-bundle-container-v2.7.0-248

update acm install

---

addon-bundling/Makefile
addon-bundling/README.md
addon-bundling/config-cert-manger.yaml
addon-bundling/retrieve-ds-bundles-cert-manger.sh
addon-bundling/retrieve-ds-bundles-dash.sh
addon-bundling/retrieve-ds-bundles.sh
addon-bundling/util.sh

https://issues.redhat.com/browse/SDA-8068 

Add CertManager Scripts

---

addon-bundling/config-cert-manger.yaml

CertManger to 1.10.2-20

---

addon-bundling/config-cert-manger.yaml

CertManger to 1.10.2-21
